name: dev-builds
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  windows-builds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: chmod +x build.sh
      
      - run: ./build.sh Print